services:
  postgres:
    image: postgres:16-alpine
    container_name: flag-check-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: flag_check_user
      POSTGRES_PASSWORD: flag_check_password
      POSTGRES_DB: flag_check_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
